import {
  IconAlertTriangle,
  IconArchive,
  IconArmchair,
  IconArrowLeft,
  IconArrowRight,
  IconBarbell,
  IconBed,
  IconBike,
  IconBooks,
  IconBox,
  IconBrandGoogle,
  IconBuilding,
  IconCalendar,
  IconCheck,
  IconChevronRight,
  IconClock,
  IconDesk,
  IconDeviceDesktop,
  IconDeviceTv,
  IconElevator,
  IconFileDescription,
  IconFish,
  IconFrame,
  IconFridge,
  IconHeart,
  IconHome,
  IconHomeFilled,
  IconLayoutGrid,
  IconLock,
  IconMail,
  IconMapPin,
  IconMinus,
  IconMapPinFilled,
  IconMenu2,
  IconMotorbike,
  IconPackage,
  IconPencil,
  IconPhone,
  IconPhoneFilled,
  IconPiano,
  IconPlant,
  IconPlus,
  IconShieldCheck,
  IconShieldCheckFilled,
  IconSofa,
  IconSquare,
  IconStar,
  IconStarFilled,
  IconTable,
  IconToolsKitchen2,
  IconTrash,
  IconTruckDelivery,
  IconWashMachine,
  IconX,
} from '@tabler/icons-react';
import type { Icon } from '@tabler/icons-react';

const ICONS: Record<string, typeof Icon> = {
  'alert-triangle':       IconAlertTriangle,
  archive:                IconArchive,
  armchair:               IconArmchair,
  'arrow-left':           IconArrowLeft,
  'arrow-right':          IconArrowRight,
  barbell:                IconBarbell,
  bed:                    IconBed,
  bike:                   IconBike,
  books:                  IconBooks,
  box:                    IconBox,
  'brand-google':         IconBrandGoogle,
  building:               IconBuilding,
  calendar:               IconCalendar,
  check:                  IconCheck,
  'chevron-right':        IconChevronRight,
  clock:                  IconClock,
  desk:                   IconDesk,
  'device-desktop':       IconDeviceDesktop,
  'device-tv':            IconDeviceTv,
  elevator:               IconElevator,
  'file-description':     IconFileDescription,
  fish:                   IconFish,
  frame:                  IconFrame,
  fridge:                 IconFridge,
  heart:                  IconHeart,
  home:                   IconHome,
  'home-filled':          IconHomeFilled,
  'layout-grid':          IconLayoutGrid,
  lock:                   IconLock,
  mail:                   IconMail,
  'map-pin':              IconMapPin,
  minus:                  IconMinus,
  'map-pin-filled':       IconMapPinFilled,
  'menu-2':               IconMenu2,
  motorbike:              IconMotorbike,
  package:                IconPackage,
  pencil:                 IconPencil,
  phone:                  IconPhone,
  'phone-filled':         IconPhoneFilled,
  piano:                  IconPiano,
  plant:                  IconPlant,
  plus:                   IconPlus,
  'shield-check':         IconShieldCheck,
  'shield-check-filled':  IconShieldCheckFilled,
  sofa:                   IconSofa,
  square:                 IconSquare,
  star:                   IconStar,
  'star-filled':          IconStarFilled,
  table:                  IconTable,
  'tools-kitchen-2':      IconToolsKitchen2,
  trash:                  IconTrash,
  'truck-delivery':       IconTruckDelivery,
  'wash-machine':         IconWashMachine,
  x:                      IconX,
};

interface Props {
  name: string;
  filled?: boolean;
  /** Used when called from Astro components */
  class?: string;
  /** Used when called from React components */
  className?: string;
  id?: string;
}

export default function TablerIcon({ name, filled, class: classProp, className, id }: Props) {
  const key = filled ? `${name}-filled` : name;
  const IconComponent = ICONS[key] ?? ICONS[name];
  if (!IconComponent) return null;
  return <IconComponent id={id} className={className ?? classProp} aria-hidden="true" />;
}
