import {
  IconAirConditioning,
  IconAlertTriangle,
  IconArchive,
  IconArmchair,
  IconArrowLeft,
  IconArrowRight,
  IconBarbell,
  IconBath,
  IconBed,
  IconBike,
  IconBooks,
  IconBottle,
  IconBox,
  IconBrandGoogle,
  IconBuilding,
  IconBulb,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconCircle,
  IconCircleDot,
  IconClock,
  IconDesk,
  IconDeviceDesktop,
  IconDeviceTv,
  IconElevator,
  IconFileDescription,
  IconFiles,
  IconFish,
  IconFlame,
  IconFrame,
  IconFridge,
  IconFriends,
  IconGlassCocktail,
  IconHanger,
  IconHeart,
  IconHome,
  IconHomeFilled,
  IconLayoutGrid,
  IconLock,
  IconMail,
  IconMapPin,
  IconMinus,
  IconMapPinFilled,
  IconMenu2,
  IconMotorbike,
  IconMusic,
  IconPackage,
  IconPencil,
  IconPhone,
  IconPhoneFilled,
  IconPiano,
  IconPlant,
  IconPlant2,
  IconPlus,
  IconRectangleVertical,
  IconShieldCheck,
  IconShieldCheckFilled,
  IconShieldLock,
  IconSofa,
  IconSquare,
  IconStairs,
  IconStar,
  IconStarFilled,
  IconTable,
  IconTools,
  IconToolsKitchen2,
  IconTractor,
  IconTrash,
  IconTruck,
  IconTruckDelivery,
  IconUmbrella,
  IconUser,
  IconWashMachine,
  IconX,
} from '@tabler/icons-react';
import type { Icon } from '@tabler/icons-react';

const ICONS: Record<string, typeof Icon> = {
  'air-conditioning':     IconAirConditioning,
  'alert-triangle':       IconAlertTriangle,
  archive:                IconArchive,
  armchair:               IconArmchair,
  'arrow-left':           IconArrowLeft,
  'arrow-right':          IconArrowRight,
  barbell:                IconBarbell,
  bath:                   IconBath,
  bed:                    IconBed,
  bike:                   IconBike,
  books:                  IconBooks,
  bottle:                 IconBottle,
  box:                    IconBox,
  'brand-google':         IconBrandGoogle,
  building:               IconBuilding,
  bulb:                   IconBulb,
  calendar:               IconCalendar,
  check:                  IconCheck,
  'chevron-down':         IconChevronDown,
  'chevron-right':        IconChevronRight,
  circle:                 IconCircle,
  'circle-dot':           IconCircleDot,
  clock:                  IconClock,
  desk:                   IconDesk,
  'device-desktop':       IconDeviceDesktop,
  'device-tv':            IconDeviceTv,
  elevator:               IconElevator,
  'file-cabinet':         IconFiles,
  'file-description':     IconFileDescription,
  fish:                   IconFish,
  flame:                  IconFlame,
  frame:                  IconFrame,
  fridge:                 IconFridge,
  friends:                IconFriends,
  'glass-cocktail':       IconGlassCocktail,
  hanger:                 IconHanger,
  heart:                  IconHeart,
  home:                   IconHome,
  'home-filled':          IconHomeFilled,
  'layout-grid':          IconLayoutGrid,
  lock:                   IconLock,
  mail:                   IconMail,
  'map-pin':              IconMapPin,
  minus:                  IconMinus,
  mirror:                 IconRectangleVertical,
  'map-pin-filled':       IconMapPinFilled,
  'menu-2':               IconMenu2,
  motorbike:              IconMotorbike,
  music:                  IconMusic,
  package:                IconPackage,
  pencil:                 IconPencil,
  phone:                  IconPhone,
  'phone-filled':         IconPhoneFilled,
  piano:                  IconPiano,
  plant:                  IconPlant,
  'plant-2':              IconPlant2,
  plus:                   IconPlus,
  'shield-check':         IconShieldCheck,
  'shield-check-filled':  IconShieldCheckFilled,
  'shield-lock':          IconShieldLock,
  sofa:                   IconSofa,
  square:                 IconSquare,
  stairs:                 IconStairs,
  star:                   IconStar,
  'star-filled':          IconStarFilled,
  table:                  IconTable,
  tools:                  IconTools,
  'tools-kitchen-2':      IconToolsKitchen2,
  tractor:                IconTractor,
  trash:                  IconTrash,
  truck:                  IconTruck,
  'truck-delivery':       IconTruckDelivery,
  umbrella:               IconUmbrella,
  user:                   IconUser,
  'wash-machine':         IconWashMachine,
  x:                      IconX,
};

interface Props {
  name: string;
  filled?: boolean;
  /** Used when called from Astro components */
  class?: string;
  /** Used when called from React components */
  className?: string;
  id?: string;
}

export default function TablerIcon({ name, filled, class: classProp, className, id }: Props) {
  const key = filled ? `${name}-filled` : name;
  const IconComponent = ICONS[key] ?? ICONS[name];
  if (!IconComponent) return null;
  return <IconComponent id={id} className={className ?? classProp} aria-hidden="true" />;
}
